name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run type-check
      - run: npm run lint
      - name: Run unit tests
        run: |
          pwd
          mkdir .jest
          echo "process.env.CLIENT_ID = '${{secrets.CLIENT_ID}}';" >> .jest/setEnvVars.js
          echo "process.env.CLIENT_SECRET = '${{secrets.CLIENT_SECRET}}';" >> .jest/setEnvVars.js
          ls .jest
          npm test
